"use client";

import { useMemo, useState, type CSSProperties } from 'react';
import { ArrowUpRight, ArrowRight, ChartNoAxesCombined, ChevronRight, CircleHelp, Download, Info, Layers3, Plus, RotateCcw, Sparkles, TrendingUp, Wallet, X } from 'lucide-react';
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip as ChartTooltip, XAxis, YAxis } from 'recharts';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Slider } from '@/components/ui/slider';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription, DialogTrigger } from '@/components/ui/dialog';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { calculateProjection, defaultPhases, frequencies, phaseRanges, type Phase } from '@/lib/compound';

const phaseColors = ['#3264df', '#62a5fb', '#85c8c5', '#aa96db', '#d9ad64', '#dd8a9f'];
const currencies: Record<string, string> = { USD: '$', EUR: '€', GBP: '£', CAD: 'CA$' };
function Choice({ value, onChange, options, label, id, className = '' }: { value: string; onChange: (value: string) => void; options: { value: string; label: string }[]; label: string; id?: string; className?: string }) {
  return <Select value={value} onValueChange={onChange}><SelectTrigger id={id} aria-label={label} className={`choice ${className}`}><SelectValue /></SelectTrigger><SelectContent position="popper">{options.map(option => <SelectItem key={option.value} value={option.value}>{option.label}</SelectItem>)}</SelectContent></Select>;
}
function NumberField({ id, label, value, onChange, prefix, suffix, min = 0, max = 1e9, step = 'any' }: { id: string; label: string; value: string; onChange: (value: string) => void; prefix?: string; suffix?: string; min?: number; max?: number; step?: string }) {
  const invalid = value.trim() === '' || !Number.isFinite(Number(value)) || Number(value) < min || Number(value) > max || (step === '1' && !Number.isInteger(Number(value)));
  return <div className="field"><Label htmlFor={id}>{label}</Label><div className={`number-wrap ${invalid ? 'invalid' : ''}`}>{prefix && <span className="prefix">{prefix}</span>}<Input id={id} type="number" inputMode="decimal" value={value} min={min} max={max} step={step} onChange={event => onChange(event.target.value)} aria-invalid={invalid} className={prefix ? 'with-prefix' : ''} />{suffix && <span className="suffix">{suffix}</span>}</div></div>;
}
export default function Home() {
  const [initial, setInitial] = useState('10000');
  const [rate, setRate] = useState('7');
  const [compounds, setCompounds] = useState('12');
  const [years, setYears] = useState('10');
  const [phases, setPhases] = useState<Phase[]>(defaultPhases);
  const [currency, setCurrency] = useState('USD');
  const [timing, setTiming] = useState<'end' | 'beginning'>('end');
  const [view, setView] = useState('growth');
  const [visible, setVisible] = useState({ total: true, contributed: true, gains: true });
  const symbol = currency === 'CAD' ? '$' : currencies[currency];
  const money = (value: number, digits = 0) => new Intl.NumberFormat('en-US', { style: 'currency', currency, minimumFractionDigits: digits, maximumFractionDigits: digits }).format(value);
  const compactMoney = (value: number) => new Intl.NumberFormat('en-US', { style: 'currency', currency, notation: 'compact', maximumFractionDigits: 1 }).format(value);
  const metricMoney = (value: number) => Math.abs(value) >= 1e8 ? compactMoney(value) : money(value);
  const validAmount = (value: string) => value.trim() !== '' && Number.isFinite(Number(value)) && Number(value) >= 0 && Number(value) <= 1e9;
  const valid = validAmount(initial) && rate.trim() !== '' && Number.isFinite(Number(rate)) && Number(rate) >= -50 && Number(rate) <= 100 && Number.isInteger(Number(years)) && Number(years) >= 1 && Number(years) <= 50 && phases.every((p, i) => validAmount(p.amount) && (i === phases.length - 1 || (Number.isInteger(Number(p.years)) && Number(p.years) >= 1 && Number(p.years) <= 50)));
  const rows = useMemo(() => valid ? calculateProjection(Number(initial), Number(rate), Number(compounds), Number(years), phases, timing) : [], [initial, rate, compounds, years, phases, timing, valid]);
  const final = rows[rows.length - 1];
  const ranges = phaseRanges(phases, Number(years) || 0);
  const growthPercent = final && final.total > 0 ? Math.max(0, final.gains) / final.total * 100 : 0;
  const donutBase = final ? final.contributed + Math.max(0, final.gains) : 0;
  const initialPercent = donutBase > 0 ? Number(initial) / donutBase * 100 : 0;
  const effectiveRate = (Math.pow(1 + Number(rate) / 100 / Number(compounds), Number(compounds)) - 1) * 100;
  const setPhase = (id: string, update: Partial<Phase>) => setPhases(current => current.map(phase => phase.id === id ? { ...phase, ...update } : phase));
  const reset = () => { setInitial('10000'); setRate('7'); setCompounds('12'); setYears('10'); setPhases(defaultPhases); setTiming('end'); setVisible({ total: true, contributed: true, gains: true }); };
  const addPhase = () => {
    const remaining = ranges.length ? ranges[ranges.length - 1].activeYears : Number(years);
    if (phases.length && remaining < 2) return;
    setPhases(current => [...current.map((p, i) => i === current.length - 1 ? { ...p, years: String(Math.max(1, Math.floor(remaining / 2))) } : p), { id: crypto.randomUUID(), amount: '200', frequency: '12', years: '1' }]);
  };
  const csvHeader = ['Year', `Contributions this year (${currency})`, `Interest this year (${currency})`, `Total contributed (${currency})`, `Total gains (${currency})`, `Balance (${currency})`];
  const csvContent = [csvHeader.join(','), ...rows.map(row => [row.year, row.addition.toFixed(2), row.interest.toFixed(2), row.contributed.toFixed(2), row.gains.toFixed(2), row.total.toFixed(2)].join(','))].join('\r\n');
  const csvHref = 'data:text/csv;charset=utf-8,' + encodeURIComponent(csvContent);
  return <div className="app-shell">
    <header className="topbar"><div className="topbar-inner"><div className="brand"><span className="brand-icon"><ChartNoAxesCombined size={21} strokeWidth={2.3} /></span>compound<span className="brand-period">.</span></div><span className="header-divider" /><span className="header-caption">A little planning. A lot of possibility.</span><Dialog><DialogTrigger asChild><Button variant="ghost" className="help-button"><CircleHelp size={17} /> How it works</Button></DialogTrigger><DialogContent className="how-dialog"><DialogHeader><DialogTitle>Make time work for your money</DialogTitle><DialogDescription>Explore how your investment and regular contributions could grow over time.</DialogDescription></DialogHeader><div className="explanation"><h3>1. Set your starting point</h3><p>Enter your initial investment, nominal annual interest rate, compounding frequency, and investment period.</p><h3>2. Build a plan that changes with you</h3><p>Each contribution phase follows the previous one. Set an amount, recurrence, and duration. The final phase automatically covers the remaining years. Set an amount to zero to pause contributions.</p><h3>3. Explore your projection</h3><p>Hover over the chart for exact figures, toggle the series, or see the yearly breakdown and export it as CSV.</p><h3>Calculation assumptions</h3><p>Growth between deposits uses the equivalent periodic rate: (1 + annual rate ÷ compounds per year) raised to the number of compounding periods elapsed. Partial periods accrue proportionally in the exponent.</p><p>A financial year uses 12 months, 52 weeks, or 26 two-week periods. Recurrence restarts at each phase. Beginning-of-period deposits earn growth during that period; end-of-period deposits start earning afterward.</p><p>Projections use a constant rate and exclude tax, fees, and inflation. Currency changes labels only and does not convert amounts.</p></div></DialogContent></Dialog></div></header>
    <main className="main-container">
      <section className="page-heading"><div><div className="eyebrow">PLAN TODAY. GROW TOMORROW.</div><h1>Compound interest calculator<span>.</span></h1><p>See what your money could become, one contribution at a time.</p></div><Choice value={currency} onChange={setCurrency} label="Currency" options={Object.entries(currencies).map(([value, sign]) => ({ value, label: `${sign}  ${value}` }))} className="currency-choice" /></section>
      {valid && final && <div className="mobile-summary" aria-live="polite"><span>Projected balance in {years} years</span><strong>{metricMoney(final.total)}</strong><small>{metricMoney(final.contributed)} contributed · {metricMoney(final.gains)} interest</small></div>}
      <div className="workspace"><aside className="controls-column" aria-label="Investment settings">
        <section className="panel settings-panel"><div className="section-heading"><h2><Wallet size={18} />Your investment</h2><Button variant="ghost" size="icon-sm" title="Reset to example" aria-label="Reset to example" onClick={reset}><RotateCcw size={15} /></Button></div><div className="settings-fields">
          <NumberField id="initial" label="Initial investment" value={initial} onChange={setInitial} prefix={symbol} />
          <div className="two-fields"><NumberField id="rate" label="Annual interest rate" value={rate} onChange={setRate} suffix="%" min={-50} max={100} /><div className="field"><Label htmlFor="compounding">Compounded</Label><Choice id="compounding" label="Compounding frequency" value={compounds} onChange={setCompounds} options={[{ value: '365', label: 'Daily' }, { value: '12', label: 'Monthly' }, { value: '4', label: 'Quarterly' }, { value: '2', label: 'Half-yearly' }, { value: '1', label: 'Yearly' }]} /></div></div>
          <NumberField id="years" label="Investment period" value={years} onChange={setYears} suffix="years" min={1} max={50} step="1" />
          <div className="years-slider"><Slider aria-label="Investment period in years" min={1} max={50} step={1} value={[Math.min(50, Math.max(1, Number(years) || 1))]} onValueChange={value => setYears(String(value[0]))} /><div className="slider-labels"><span>1 year</span><span>50 years</span></div></div>
        </div></section>
        <section className="panel contribution-panel"><div className="section-heading"><h2><Layers3 size={18} />Contribution plan</h2><span className="small-badge">{phases.length} {phases.length === 1 ? 'phase' : 'phases'}</span></div><p className="panel-intro">Life changes. Your contributions can, too.</p><div className="phases">{ranges.map((phase, index) => <div className="phase-card" key={phase.id} style={{ '--phase-color': phaseColors[index % phaseColors.length] } as CSSProperties}><div className="phase-heading"><span className="phase-number">{String(index + 1).padStart(2, '0')}</span><strong>{phase.activeYears > 0 ? phase.activeYears === 1 ? `Year ${phase.start + 1}` : `Years ${phase.start + 1}–${Math.min(phase.end, Number(years))}` : 'Outside horizon'}</strong><Button variant="ghost" size="icon-sm" className="remove-phase" aria-label={`Remove phase ${index + 1}`} onClick={() => setPhases(current => current.filter(p => p.id !== phase.id))}><X size={15} /></Button></div><div className="phase-inputs"><NumberField id={`amount-${phase.id}`} label={`Phase ${index + 1} amount`} value={phase.amount} onChange={amount => setPhase(phase.id, { amount })} prefix={symbol} /><Choice label={`Phase ${index + 1} recurrence`} value={phase.frequency} onChange={frequency => setPhase(phase.id, { frequency })} options={frequencies} /></div><div className="phase-duration">{index === phases.length - 1 ? <><ArrowRight size={13} /><span>For the remaining <b>{phase.activeYears} {phase.activeYears === 1 ? 'year' : 'years'}</b></span></> : <><Label htmlFor={`duration-${phase.id}`}>For</Label><Input id={`duration-${phase.id}`} aria-label={`Phase ${index + 1} duration in years`} className="duration-input" type="number" min={1} max={50} step={1} value={phase.years} onChange={event => setPhase(phase.id, { years: event.target.value })} aria-invalid={!Number.isInteger(Number(phase.years)) || Number(phase.years) < 1 || Number(phase.years) > 50} /><span>{Number(phase.years) === 1 ? 'year' : 'years'}</span><span className="then-label">then <ChevronRight size={12} /></span></>}</div></div>)}</div>
          {phases.length === 0 && <p className="empty-phases">Your initial investment grows on its own. Add a phase to make regular contributions.</p>}
          <Button variant="outline" className="add-phase" onClick={addPhase} disabled={!valid || (phases.length > 0 && ranges[ranges.length - 1].activeYears < 2)}><Plus size={16} />Add contribution phase</Button>
          {phases.length > 0 && ranges[ranges.length - 1].activeYears < 2 && <p className="limit-note">Shorten an earlier phase or extend the investment period to add another.</p>}
          {ranges.some(p => p.end > Number(years)) && <p className="limit-note">Only contributions within the investment period are included.</p>}
          <div className="timing-field"><Label htmlFor="timing">Contributions made</Label><Choice id="timing" label="Contribution timing" value={timing} onChange={value => setTiming(value as 'end' | 'beginning')} options={[{ value: 'end', label: 'End of each period' }, { value: 'beginning', label: 'Beginning of each period' }]} /></div>
        </section>
      </aside><section className="results-column" aria-label="Investment projection">
        {!valid || !final ? <div className="panel validation" role="alert"><Info size={28} /><h2>Let’s check those numbers</h2><p>Enter amounts from 0 to 1 billion, an annual rate from −50% to 100%, and whole-year durations from 1 to 50.</p></div> : <>
          <div className="metric-grid" aria-live="polite" aria-atomic="true"><section className="metric total-metric"><div className="metric-label">Projected balance<ArrowUpRight size={20} /></div><strong title={money(final.total, 2)}>{metricMoney(final.total)}</strong><span>At the end of {years} {Number(years) === 1 ? 'year' : 'years'}</span></section><section className="metric"><div className="metric-label"><span className="legend-square contributions-dot" />Total contributed</div><strong title={money(final.contributed, 2)}>{metricMoney(final.contributed)}</strong><span>Your money put to work</span></section><section className="metric"><div className="metric-label"><span className="legend-square gains-dot" />{final.gains < 0 ? 'Investment loss' : 'Interest earned'}</div><strong className={final.gains < 0 ? 'loss-text' : 'gain-text'} title={money(final.gains, 2)}>{metricMoney(final.gains)}</strong><span>{final.contributed > 0 ? `${final.gains >= 0 ? '+' : ''}${(final.gains / final.contributed * 100).toFixed(1)}% on contributions` : 'Growth on your investment'}</span></section></div>
          <section className="panel chart-panel"><Tabs value={view} onValueChange={setView}><div className="chart-header"><div><h2>Your money over time</h2><p>A clearer picture of your future balance.</p></div><TabsList aria-label="Projection view"><TabsTrigger value="growth"><TrendingUp size={15} />Growth</TabsTrigger><TabsTrigger value="table">Year by year</TabsTrigger></TabsList></div><TabsContent value="growth"><div className="chart-legend">{([{ key: 'total', label: 'Total balance', color: '#3264df' }, { key: 'contributed', label: 'Contributions', color: '#a5bcd9' }, { key: 'gains', label: 'Interest', color: '#42aaa5' }] as const).map(series => <button key={series.key} type="button" aria-pressed={visible[series.key]} onClick={() => setVisible(current => ({ ...current, [series.key]: !current[series.key] }))} className={!visible[series.key] ? 'legend-inactive' : ''}><i style={{ background: series.color }} />{series.label}</button>)}<span>{currency}</span></div>
            <div className="growth-chart" role="img" aria-label={`After ${years} years: balance ${money(final.total)}, contributions ${money(final.contributed)}, interest ${money(final.gains)}. Exact annual values are in the Year by year tab.`}><ResponsiveContainer width="100%" height="100%" minWidth={0} initialDimension={{ width: 600, height: 305 }}><AreaChart data={rows} margin={{ top: 20, right: 12, left: 0, bottom: 5 }}><defs><linearGradient id="totalFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#4e80ec" stopOpacity={0.19} /><stop offset="100%" stopColor="#4e80ec" stopOpacity={0.015} /></linearGradient><linearGradient id="contributionFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#b5c9e4" stopOpacity={0.4} /><stop offset="100%" stopColor="#b5c9e4" stopOpacity={0.08} /></linearGradient></defs><CartesianGrid strokeDasharray="3 5" vertical={false} stroke="#e9eef3" /><XAxis dataKey="year" tickFormatter={value => `Yr ${value}`} axisLine={false} tickLine={false} tick={{ fill: '#7b879a', fontSize: 12 }} minTickGap={30} dy={10} /><YAxis tickFormatter={compactMoney} axisLine={false} tickLine={false} tick={{ fill: '#7b879a', fontSize: 12 }} width={70} tickCount={5} /><ChartTooltip formatter={(value, name) => [money(Number(value), 2), name]} labelFormatter={label => `Year ${label}`} contentStyle={{ border: '1px solid #e4eaf2', borderRadius: 12, fontSize: 13, boxShadow: '0 8px 32px #18294712' }} /><Area hide={!visible.total} type="monotone" dataKey="total" name="Total balance" stroke="#3264df" strokeWidth={3} fill="url(#totalFill)" isAnimationActive={false} /><Area hide={!visible.contributed} type="monotone" dataKey="contributed" name="Contributions" stroke="#a5bcd9" strokeWidth={2} fill="url(#contributionFill)" isAnimationActive={false} /><Area hide={!visible.gains} type="monotone" dataKey="gains" name="Interest" stroke="#42aaa5" strokeWidth={2} strokeDasharray="5 4" fill="transparent" isAnimationActive={false} /></AreaChart></ResponsiveContainer></div><div className="chart-axis-title">INVESTMENT YEARS</div>
          </TabsContent><TabsContent value="table"><div className="year-table"><Table><TableHeader><TableRow><TableHead>Year</TableHead><TableHead>Added</TableHead><TableHead>Interest</TableHead><TableHead>Contributed</TableHead><TableHead>Balance</TableHead></TableRow></TableHeader><TableBody>{rows.map(row => <TableRow key={row.year}><TableCell>{row.year === 0 ? 'Start' : row.year}</TableCell><TableCell>{money(row.addition, 2)}</TableCell><TableCell className={row.interest >= 0 ? 'gain-text' : 'loss-text'}>{money(row.interest, 2)}</TableCell><TableCell>{money(row.contributed, 2)}</TableCell><TableCell className="balance-cell">{money(row.total, 2)}</TableCell></TableRow>)}</TableBody></Table></div></TabsContent></Tabs><div className="chart-bottom"><span><span className="live-dot" />Updates as you make changes</span><Button variant="ghost" asChild><a href={csvHref} download={`compound-projection-${currency}.csv`}><Download size={15} />Export CSV</a></Button></div></section>
          <section className="panel breakdown-panel"><div className="breakdown-main"><h2>{final.gains < 0 ? 'Where your contributions come from' : 'What makes up your balance?'}</h2><div className="breakdown-content"><div className="donut" role="img" aria-label={`${growthPercent.toFixed(1)} percent of balance is interest`} style={{ background: donutBase === 0 ? '#e8edf5' : `conic-gradient(#42aaa5 0 ${growthPercent}%,#a5bcd9 ${growthPercent}% ${100 - initialPercent}%,#253e68 ${100 - initialPercent}% 100%)` }}><div><strong>{growthPercent.toFixed(0)}<span>%</span></strong><small>from interest</small></div></div><div className="breakdown-legend"><div><span><i style={{ background: '#253e68' }} />Initial investment</span><b>{metricMoney(Number(initial))}</b></div><div><span><i style={{ background: '#a5bcd9' }} />Regular additions</span><b>{metricMoney(final.contributed - Number(initial))}</b></div><div><span><i style={{ background: final.gains < 0 ? '#b83f51' : '#42aaa5' }} />{final.gains < 0 ? 'Investment loss' : 'Interest earned'}</span><b className={final.gains < 0 ? 'loss-text' : 'gain-text'}>{metricMoney(final.gains)}</b></div></div></div></div><div className="insight"><span className="insight-icon"><Sparkles size={18} /></span><h3>{final.gains < 0 ? 'See the full picture' : 'The power of staying invested'}</h3><p>{final.gains < 0 ? <>At this rate, your projection includes a loss of <b>{metricMoney(-final.gains)}</b>. Try another rate to explore a different outcome.</> : final.gains === 0 ? <>Your balance comes entirely from your contributions. Try a positive interest rate to see the effect of compounding.</> : <>Over {years} years, your money could earn <b>{metricMoney(final.gains)}</b> of its own.</>}</p><span>{effectiveRate.toFixed(2)}% effective annual rate<ArrowUpRight size={14} /></span></div></section>
          <section className="panel timeline-panel"><div className="timeline-title"><h2>Your contribution journey</h2><span>{years}-year plan</span></div><div className="timeline-bar">{ranges.filter(p => p.activeYears > 0).map((p, index) => <div key={p.id} style={{ flex: p.activeYears, background: phaseColors[index % phaseColors.length] }} title={`${p.activeYears} years: ${money(Number(p.amount))} ${frequencies.find(f => f.value === p.frequency)?.label.toLowerCase()}`} />)}{phases.length === 0 && <div style={{ flex: 1, background: '#e6ebf2' }} />}</div><div className="timeline-labels">{ranges.filter(p => p.activeYears > 0).map((p, index) => <div key={p.id}><i style={{ background: phaseColors[index % phaseColors.length] }} /><span><strong>{metricMoney(Number(p.amount))}<small> / {p.frequency === '12' ? 'month' : p.frequency === '52' ? 'week' : p.frequency === '26' ? '2 weeks' : p.frequency === '4' ? 'quarter' : p.frequency === '2' ? 'half-year' : 'year'}</small></strong><em>{p.activeYears === 1 ? `Year ${p.start + 1}` : `Years ${p.start + 1}–${Math.min(p.end, Number(years))}`}</em></span></div>)}</div></section>
          <p className="projection-note"><Info size={15} /><span>Illustrative projections. Returns aren’t guaranteed. Taxes, fees, and inflation aren’t included.</span></p>
        </>}
      </section></div><footer><span className="footer-brand">compound.</span><span>Built for your long game.</span><span className="footer-right">Small contributions. Meaningful growth.</span></footer>
    </main>
  </div>;
}
